### ISSUE TITLE
Private message

### ISSUE THREAD

**Issue by wojtekidd** [ckeditor/editor-recommendations#11]
What about _'Private Message'_ as another use case? Online editors are often used for that purpose, whether it's writing e-mails online or any other type of 1-1 / 1-many type of private messages. These often include signatures, quotes from other messages as reference etc.

**Comment by Comandeer** [comment]
It seems like the good use case to describe as it's very different from blog/article one.

Can you come up with ideas for that use case's features? At the moment I can think of:
- signatures, as you already mentioned
- quotes, also from you
- some typographical conventions (bold, italic…)
- links with autolinking – maybe also with link's preview?
- emoticons/emojis (is there anyone not using them while writing PM?)

The e-mails could be more troublesome than generic private messages as they tend to be more and more complicated. We already have "email design" – they are just like pages. So for them IMO the minimum are the features already mentioned + inserting images.

There is also problem with attachments to e-mails and PM-s, e.g. Messenger allows to paste image directly into message. In the case of e-mails I'm not sure if uploads are even the part of editor…

I also wouldn't be angry if you prepare some nice PR with draft of that use case ;)

**Comment by Comandeer** [comment]
First draft for that use case [is available](http://ckeditor.github.io/editor-recommendations/use-cases/private-message.html).

**Comment by Comandeer** [comment]
Use cases seems to be stable, without any changes. Let's just drop "draft" label from them!
