### ISSUE TITLE
Combine Use Cases: Article Comments with Private Message

### ISSUE THREAD

**Issue by wojtekidd** [ckeditor/editor-recommendations#16]
It looks like both of these use cases are pretty similar and will require the same set of features. How about merging them into one use case?

**Comment by Comandeer** [comment]
I don't know if it is the best way to go. These use cases serve different purposes. We have "Blog/Article" use case, but honestly – can anyone tell the main difference between blog and article (aren't they just different names for the same thing?)? In that case difference between private message and article comments is much more visible and easier to define.

**Comment by wojtekidd** [comment]
I agree, however we might end up with two different use cases having identical features and usability features.

**Comment by Comandeer** [comment]
But different purposes ;)

Also I'm not so sure if the features list would be exactly the same. Comments systems are often very light – look at Disqus: just plain text (and some allowed HTML, if someone is really determined). I don't think that users would e.g. insert lists in comment. There are also more and more comment systems that support Markdown (e.g. this one). So features could really vary.
