### ISSUE TITLE
Quote

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/editor-recommendations#18]
Quote is a main way to introduce text from other sources. There are two types of quotes:
- **inline**, marked up with [`q` element](https://www.w3.org/TR/html5/text-level-semantics.html#the-q-element);
- **block**, marked up with [`blockquote` element](https://www.w3.org/TR/html5/grouping-content.html#the-blockquote-element).

I think that we should stick with `blockquote` element.

It is also worth noting that quotes can be placed inside `figure` (to act as standalone "Widget") and are usually accompanied by `cite` element that provides reference to the source of quote.

**Comment by fredck** [comment]
My opinion is that "inline quotes" would be seen as an extra feature for those who really want it. In the other hand, "block quotes" may be standard features which should be part of the recommendations.

**Comment by Comandeer** [comment]
I've added a draft for "Quote". Current version is based on `figure` element, but I feel that we can think about simplifying it by dropping the figure and sticking to the `blockquote > footer` pattern:

``` html
<blockquote cite="https://pl.wikisource.org/wiki/Pan_Tadeusz_(wyd._1834)/Ksi%C4%99ga_pierwsza">
    <p>Litwo! Ojczyzno moja! ty jesteś jak zdrowie.<br>
    Ile cię trzeba cenić, ten tylko się dowie,<br>
    Kto cię stracił. Dziś piękność twą w całej ozdobie<br>
    Widzę i opisuję, bo tęsknię po tobie.</p>
    <footer><cite>Adam Mickiewicz, <i>Pan Tadeusz</i></cite></footer>
</blockquote>
```

**Comment by fredck** [comment]
I like the use of `<figure>` because it gives a clearer separation between the quote text and the text that describes the source, which as a matter of fact is not part of the quote (note that the quote text already have the `cite` attribute for the reference purpose).

I've also see that this is the standard for [A List Apart](http://alistapart.com/blog/post/more-thoughts-about-blockquotes-than-are-strictly-required): https://gist.github.com/murtaugh/4489740

**Comment by fredck** [comment]
Btw, I understand the wish to diffuse the Polish culture, but the examples and references linking should be in English and to English sources. English is our choice for a "culture free", global communication.

**Comment by Comandeer** [comment]
Ok, I've updated example to "Apollo 11" excerpt from Wikipedia.

**Comment by Comandeer** [comment]
Ok, it seems like a stable feature. I propose moving it from draft to the recommendation status. I'll wait 3 days for objections and then do what should be done ;)
