### ISSUE TITLE
<figure> based Widget feature

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/editor-recommendations#20]
As it was pointed in #14, `figure` element can be used in more wide context than only images. Therefore it can be used as a base for more generic "Widget" feature that can be used to create other features, such as:
-  Image (#14)
- Standalone quotes (#18)
- Tables with caption
- Media embeds

and many more.

The most tricky part is to correctly interpret HTML 5 specification, which says (bold's mine):

> The figure element represents some flow content, optionally with a caption, that is **self-contained** (like a complete sentence) and is typically referenced as a single unit from the main flow of the document.

So any thing that is dependent on context (e.g. emoticon or inline quote) can't be marked that way.

The question is if we want to create such feature, that would act as a base for many other features. It will introduce some kind of hierarchy to our set of recommendations, being a dependency for other features. Is it worth trouble?

**Comment by Comandeer** [comment]
I've added draft for this feature: http://ckeditor.github.io/editor-recommendations/features/widget.html

**Comment by Reinmar** [comment]
Why does the page mix widgets with figures? Aren't widgets something much more generic?

**Comment by Comandeer** [comment]
I'm not so sure if that things are so different… Let's look at the use-cases of widgets in the CKE4:
- Images
- Code snippets
- Embeds

Probably the biggest non-content widget is upload widget, which is used mainly for… images ;)

Actually nearly all widgets that are available in CKE4 could be expressed via `figure` element.

**Comment by fredck** [comment]
Hum… I have a feeling that we’re going towards implementation details here, while we should limit to discuss about the final features specifically. In other words, we talk about code, blockquote, images, etc, without having to include them in a implementation model that fits all of them.

I don’t see fit for this in the ER. Seems to be pointless.

**Comment by Comandeer** [comment]
Ok, I've dropped the draft.
