### ISSUE TITLE
Strikethrough

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/editor-recommendations#3]
That feature is probably also neccessary, as it's the easiest way to mark something as not longer appropiate or had been deleted.

Therefore we should consider two elements for that:
- [`s` element](http://www.w3.org/TR/html5/text-level-semantics.html#the-s-element) - the most generic element used to mark something not longer relevant
- [`del` element](http://www.w3.org/TR/html5/edits.html#the-del-element) - the element used to mark the removal of some parts of content (it probably suits better to some kind of "Suggestions" feature, but should be also considered here).

CKE4 is using `s` or `strike` elements for it as a part of [basicstyles plugin](https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/basicstyles/plugin.js).

**Comment by fredck** [comment]
In my personal opinion, `s` is the one and only way to go.

**Comment by Comandeer** [comment]
`s` is more generic, so it can be "abused" to use cases where `del` is more appropiate (as document edits are also the parts of content that are not longer relevant), so I also think that it's better choice here. `del` is too "formal" for generic feature (datetimes, sources of edit…) - it's intended to be uses in documents such as HTML5 spec.

**Comment by Comandeer** [comment]
Some stats. I've checked [22 editors](https://gist.github.com/Comandeer/623b317e09af53c75e46) to see how they implement some basic features.

"Strike" is absent in 9 editors, the rest implements it as follows:
- 4 of them use `s`
- 4 of them use `strike`
- 2 of them use `span[style]`
- 2 of them use `del`
- 1 uses own syntax, based on XML (`text:span`)

**Comment by Comandeer** [comment]
Actually the name of that feature is "strikethrough", not "strike". I've changed it.

**Comment by Comandeer** [comment]
I created the first version of draft for that feature: http://ckeditor.github.io/editor-recommendations/features/strikethrough.html
Feel free to comment or even prepare some PR to improve it!

**Comment by Comandeer** [comment]
Ok, it seems like a stable feature. I propose moving it from draft to the recommendation status. I'll wait 3 days for objections and then do what should be done ;)
