### ISSUE TITLE
The project's main page misses "whys" and "whats" section

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/editor-recommendations#33]
There should be an intro on http://ckeditor.github.io/editor-recommendations/ what this project is all about, for whom it's created, by whom, where to contribute, how to contribute, etc.

**Comment by wojtekidd** [comment]
How about this: http://ckeditor.github.io/editor-recommendations/about/

**Comment by Reinmar** [comment]
Hehe... so I guess that this means that the main page must be rethought. I haven't even looked at the top  menu bar.

**Comment by Comandeer** [comment]
Maybe just add section above "Editing Features" named "About project"?

**Comment by Comandeer** [comment]
I've added "call to action" button in the jumbotron, which leads to about page. No more need to looking at the top menu bar ;)

@Reinmar, is that solution satisfying or not really?

**Comment by Reinmar** [comment]
Fine for me. Thanks.
