### ISSUE TITLE
The text column should be more narrow

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/editor-recommendations#37]
Now, on my screen, it has 950px what makes the text very hard to read. It shouldn't have more than 700px.

Now:

<img width="945" alt="screen shot 2016-02-29 at 12 16 15" src="https://cloud.githubusercontent.com/assets/156149/13392967/afc3be1a-dede-11e5-9614-1ee5cf9aca33.png">

Much better:

<img width="638" alt="screen shot 2016-02-29 at 12 20 45" src="https://cloud.githubusercontent.com/assets/156149/13392992/e12c5aa2-dede-11e5-8cb3-44815e3259fb.png">

**Comment by Comandeer** [comment]
Is it better now? I've narrowed the paragraphs' width.

**Comment by Reinmar** [comment]
It's better, but a pity that all this now went so far to the left :D. Couldn't you make the container narrower?

**Comment by Comandeer** [comment]
Ok… I've narrowed whole container… but now sidebar is not nice enough.

**Comment by Reinmar** [comment]
9:3 looks fine IMO.

<img width="1173" alt="screen shot 2016-02-29 at 14 55 40" src="https://cloud.githubusercontent.com/assets/156149/13396381/86a8d9a0-def4-11e5-95a7-d18d096afaad.png">

**Comment by Comandeer** [comment]
Ok, I'll close it for now.

**Comment by Reinmar** [comment]
I meant that I had to tune it manually :P I'll make a PR.
