### ISSUE TITLE
Keystrokes notation

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/editor-recommendations#39]
We write keystrokes as <kbd>Ctrl + sth</kbd>. Those are correct for Windows and Linux, but for MacOSX users we should use <kbd>Command</kbd>.

How can we resolve this?
1. Have a separate page clarifying that Ctrl is to be replaced by Cmd on MacOSX devices.
2. Duplicate all keystrokes.
3. Use some other notation.

**Comment by Comandeer** [comment]
http://ckeditor.github.io/editor-recommendations/general-policies/ → last section. So it probably covers your point 1.

**Comment by fredck** [comment]
That policy has been created exactly to clarify that and make the documentation clearer. I would not make any further steps.

**Comment by Reinmar** [comment]
OK. I forgot I've seen it there. We could add some (*) to keystrokes but it's not super important.
