### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/editor-recommendations#40]
At the moment, recommendations don't have any mechanism to highlight HTML's syntax. Maybe we should add some script for it?

There are two main candidates:
- [Prism.js](http://prismjs.com/)
- [GeSHi](http://qbnz.com/highlighter/)

**Comment by Reinmar** [comment]
https://highlightjs.org/

**Comment by fredck** [comment]
I think that this is totally out of the scope of the recommendation. It's an optional feature totally up to the editor developer to propose.

**Comment by Comandeer** [comment]
I was thinking about examples in our drafts, because they don't look much friendly without highlight. I don't propose highlighting as a feature.

**Comment by fredck** [comment]
Hahahaha... totally misunderstood this... ofc it makes sense now :D

**Comment by Comandeer** [comment]
I've added highlight.js, but default GH Pages highlighter (Rogue) is messing with it… I switched off Jekyll's highlighter on the local dev server, but it seems not to work on GH :/

**Comment by Reinmar** [comment]
> Hahahaha... totally misunderstood this...

:D me too

**Comment by Comandeer** [comment]
Guys, I'd like to remind you that there is something called "labels" and I think that "meta" label is clear enough :P

**Comment by Comandeer** [comment]
Ok, I've changed code highlighter to rouge (if we had choice…) and added Monokai styles from [Pygments](http://pygments.org/) – I've added also info about it in ["About" page](http://ckeditor.github.io/editor-recommendations/about/#license). Now it's working!
