### ISSUE TITLE
Tab key behavior

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/editor-recommendations#41]
As @fredck pointed in #19 , we should include some information about desired `Tab` key behavior.

For now we have only one proposal:

`Tab` key pressed when cursor is at the beginning of the list item should indent that list item.

Probably we can think about binding `Tab` to indenting text (as it's done in offline text editors), however it could make the editor inaccessible (`Tab` is used mainly to navigate between page's elements).

**Comment by fredck** [comment]
I don't see "feature related" keystrokes as something that should be grouped as a single Usability Feature. In #19, the use of `Tab` is a essential UX aspect that enable specific implementation details of the feature. It's much like the `Ctrl+<Key>` thing.

If we would ever have to spec `Tab` we should do this independently of the features, just like the `Enter` key. For example, we may spec that the `Tab` key can be used to enter and leave the editor and that features may override this behavior to match their specific needs.

**Comment by Comandeer** [comment]
> For example, we may spec that the Tab key can be used to enter and leave the editor and that features may override this behavior to match their specific needs.

Hmm… sounds reasonable. Probably something similar should be specced for `Enter` key (something like "`Enter` key inserts new block context, default to paragraph, but it can be changed by certain features").

My first idea was to describe `Tab` and `Enter` keys in diffrent contexts, but splitting it between particular features probably will be more readable.

**Comment by Comandeer** [comment]
Ok, I've created the first version of the draft: http://ckeditor.github.io/editor-recommendations/usability/tab-key.html

**Comment by Comandeer** [comment]
Ok, it seems like a stable feature. I propose moving it from draft to the recommendation status. I'll wait 3 days for objections and then do what should be done ;)
