### ISSUE TITLE
Article comments

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/editor-recommendations#42]
Actually that use case would use very similar features set as "Private Message" one (#11), but it is so common use case that I think it should be mentioned.

The draft is already available: http://ckeditor.github.io/editor-recommendations/use-cases/article-comments.html

**Comment by fredck** [comment]
I don't see "Image" as a common feature for comments. This may be solution specific and the spec must consider the most common (obvious) case. As any other Use Case, one can always decide to add or remove features to the recommended set.

**Comment by Comandeer** [comment]
I wa going to prove that I'm right, but I haven't found any comments with images… So maybe it's not as popular as I used to think ;)

Dropped "Image" from "Features" list already.

**Comment by wojtekidd** [comment]
I don't want to mess things up, but it's pretty common to have animated GIFs or images in general in comments on social media. It might be just a matter of time when these tendency shifts to comments on blogs and other platforms. Just a thought.

**Comment by Comandeer** [comment]
> It might be just a matter of time

But for now @fredck is probably right and "Image" is still an additional feature, not basic one.

**Comment by CanRau** [comment]
Just adding my two cents..would say you're right that images are still not so common..
We had images in our comments once, found it especially interesting for our recipe articles where we asked readers to not only tell how they liked it but show image too. After major change on our blog it's still missing but I'm looking forward implementing images in comments again as I think it can be quite fun :-)
Saludos

**Comment by Comandeer** [comment]
Use cases seems to be stable, without any changes. Let's just drop "draft" label from them!
