### ISSUE TITLE
Improve syntax highlighting contrast

### ISSUE THREAD

**Issue by vokiel** [ckeditor/editor-recommendations#45]
Used theme tags contrast is not accessible.

> Contrast Ratio: 3.9:1
> Normal Text:
> 
> AA: **Fail**
> AAA: **Fail**
> 
> Large Text:
> 
> AA: **Pass**
> AAA: **Fail**

**Comment by Comandeer** [comment]
Rogue syntax highlighter is using Pygments-compatible skins, so probably we could just select one with better contrast from the list: https://help.farbox.com/pygments.html (the choice is rather obvious as Borland style seems to be the only one without any contrast errors according to [WAVE](http://wave.webaim.org/report#/https://help.farbox.com/pygments.html)…).

**Comment by Comandeer** [comment]
Ok, I've changed style to Borland one and tweaked some colors. Now the page is passing the WAVE test.

**Comment by Comandeer** [comment]
Seems that it's no longer an issue. Closing.
