### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/editor-recommendations#46]
More and more often created content should be delivered in multiple languages. There is also the type of content in which the two or more languages are mixed. Therefore there is a need to deliver editor that could support many languages.

There are two challenges in multilang editor:
- Support for LTR and RTL languages.
- Support for [WCAG 3.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/meaning-other-lang-id.html) by identifying every language that appears in the content.

The first one could be achieved by using [the `[dir]` attribute](https://www.w3.org/TR/html5/dom.html#the-dir-attribute) with `ltr` or `rtl` values on specific paragraphs or other block context:

``` html
<p dir="rtl">Right to left text.</p>
```

The second one could be achieved by using [the `[lang]` attribute](https://www.w3.org/TR/html5/dom.html#the-lang-and-xml:lang-attributes) with value from [BCP47](http://www.ietf.org/rfc/bcp/bcp47.txt) on specific paragraphs or other block context:

``` html
<p lang="pl">Przykładowy tekst w innym języku.</p>
```

Of course that attributes could be joined together if the text is in foreign language and it's RTL:

``` html
<p lang="en" dir="rtl">Suppose that it's some foreign language.</p>
```

---

I'm not 100% sure however if we should add this feature to the recommendations as it's only "nice-to-have", not "must-have".

**Comment by fredck** [comment]
What about text fragments, like: "In French one would say _bonjour_ when entering the bar."

**Comment by Comandeer** [comment]
Hm… So probably we should allow adding this attributes to all elements, not only block ones. We should also allow creating new elements just to indicate language or text direction.

**Comment by fredck** [comment]
We're talking about editor features, not HTML... therefore we must understand how the editor feature should look like to properly support this. Much probably we're talking about dedicated tagging for it.

**Comment by Comandeer** [comment]
I was thinking about current implementation of that features in CKE: http://ckeditor.com/addon/language and http://ckeditor.com/addon/bidi – and there's "block-level content" phrase in description. And that's why I wrote initially about block context. And then writing about adding attributes to all elements, I was still thinking about button ;)

But honestly I don't feel that button is the best option for such features, however I don't have better idea (yet).

**Comment by Comandeer** [comment]
There is no interest in this feature so far, so I'm closing this issue. If we'd want to review it in the future, then I'll reopen the issue.
