### ISSUE TITLE
Optional "pro" features

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/editor-recommendations#47]
Basic set of features for the editor is _de facto_ ready. But there are some really "nice-to-have" features (eg. #46) and I'm not sure if we should ignore them or add to the recommendations.

The point is: are recommendations intended to include only basic and essential features for editor or is there also a place for some more "pro" features, which are optional?

There is also an idea of "conformance levels", similar to the ones defined in WCAG standard (1. level – basic features, 2. level – basic features + optional ones etc.), but I feel that it's an overkill.

**Comment by fredck** [comment]
I think that, when it comes to features, it is fine to have many more... the fact is that we don't need to have then included in Use Cases and they'll just stay as features which one can optionally include on their setups.

**Comment by Comandeer** [comment]
So to sum up: if someone propose a nice feature, it could be added to a set of features.
