### ISSUE TITLE
Add Google Tag Manager

### ISSUE THREAD

**Issue by vokiel** [ckeditor/editor-recommendations#48]
So we'll be able to see what content is the most popular.

**Comment by mlewand** [comment]
If it goes there, it would definitely have to be opt-in as it would be a privacy issue otherwise.

**Comment by vokiel** [comment]
@mlewand I'm thinking about section on **About** page where we'll write that we use GTM and describe in one sentence what this is done for.

**Comment by vokiel** [comment]
PR in #49

**Comment by Comandeer** [comment]
I'm not sure if such short note is enough. I don't know how exactly GTM is working, but if it's using some cookies, shouldn't we include info about them to comply with "cookie law"?

**Comment by vokiel** [comment]
Text we already have on other websites.

> We may store information about you in cookies (files which are sent by us to your computer or other access device) which we can access when you visit our site in the future. If you want to delete any cookies that are already on your computer, please refer to the instructions of your file management software to locate the file or directory that stores cookies. If you want to stop cookies from being stored on your computer in the future, please refer to your browser manufacturer's instructions by clicking "Help" in your browser menu. Further information on deleting or controlling cookies is available at [www.AboutCookies.org](http://www.aboutcookies.org).

**Comment by Comandeer** [comment]
Ok, PR looks good, merged.
