### ISSUE TITLE
Using "bold" or "italic" when selection is collapsed in the middle of a word.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/editor-recommendations#50]
This is a proposal to discuss what is the optimal editor behavior when a user has a selection collapsed in the middle of a word and then presses "bold" or "italic" button (or uses appropriate key shortcut).

Currently, CKE4 (and also CKE5 at current state) will just "remember" that the button was clicked and will let you write in chosen format. One could say that the format was set "on selection".

Some editors (desktop offline solutions and those available on the Web) have a different behavior. Instead of setting format "on selection", they change the whole word to the chosen format. So `<p>foo b^ar lol</p>` after using "bold" becomes `<p>foo <strong>b^ar</strong> lol</p>`.

**Comment by Comandeer** [comment]
As there is no real discussion on this issue, I'm closing it.
