### ISSUE TITLE
Profanity filter

### ISSUE THREAD

**Issue by RamuRChenchaiah** [ckeditor/editor-recommendations#53]
Hi ,

Do we have any profanity filter for the Editor. I did check some sites, no luck.

Regards
Ramu

**Comment by Comandeer** [comment]
Hi,

sorry for responding so late.

This repository is a place to discuss about a set of recommendations on how the ideal rich text editor should behave – there aren't any real solutions or plugins, just ideas backed with some research.

If you're looking for such filter for CKEditor 4, you can search our [Addons page](http://ckeditor.com/addons/plugins/all).
