### ISSUE TITLE
Lists – enter should insert new list item after the current one

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/editor-recommendations#55]
> Enter inside a non-empty list item SHOULD insert a new list item before the current list item.

I think it should be "after".

**Comment by Comandeer** [comment]
Actually I think it's more like splitting list item, e.g.

```markdown
* te^st
```

would produce

```markdown
* te
* ^st
```

Actually this description is probably based on the following situation:

```markdown
* ^test
```

In this case list item is "split" and the empty half seems to be inserted _before_ the current list item.

I propose changing the description into:

> <kbd>Enter</kbd> inside a non-empty list item SHOULD split the current list item into two, depending on the position of caret.
