### ISSUE TITLE
Error in React

### ISSUE THREAD

**Issue by jkiss** [ckeditor/editor-recommendations#56]
ckeditor is a awsome rich editor, but it's not friendly with ES6 import, it will be a big change if ckeditor can support UMD 😃

**Comment by Comandeer** [comment]
This repository is dedicated to create a set of recommendations for creating Rich Text Editors. To post a new feature request for CKEditor 4, please [file an issue in its repository](https://github.com/ckeditor/ckeditor-dev/issues). In case of CKEditor 5 the issue of modules should be already addressed.
