### ISSUE TITLE
empty list/array brackets gets removed by Ckeditor

### ISSUE THREAD

**Issue by metulburr** [ckeditor/editor-recommendations#58]
for example when using the editor with python in the codebox

```
lst = []
for i in range(5):
    lst.append(i)
 
print(lst)
```

This will get turned into this by Ckeditor

```
lst = 
for i in range(5):
    lst.append(i)
 
print(lst)
```

**Comment by Comandeer** [comment]
This repository is dedicated for working on a set of recommendations on how modern Rich Text Editors should work. If you want to report bug in CKEditor 4, please [fill the issue in its repostiory](https://github.com/ckeditor/ckeditor-dev/issues/new).
