### ISSUE TITLE
Bulleted/numbered list names are non-semantic

### ISSUE THREAD

**Issue by mlewand** [ckeditor/editor-recommendations#59]
This is something that was bugging me for awhile.

Names like "bulleted" / "numbered" list are non-semantic, as they emphasize on visuals rather than actual meaning.

It's perfectly fine for bullet (a.ka. unordered) list to be marked by circles, triangles, emojis or anything else.

It's also fine for number (a.ka. ordered) list to use letters, or any other symbol that makes a sequence - and it doesn't have to be a number.

**Comment by Comandeer** [comment]
Please see "Notes" section in Bulleted List or Numbered List recommendations:

> Although this feature should be called “Unordered List”, for historical reasons users are used to the “Bulleted List” name. Therefore, for consistency and due to better recognition, this feature SHOULD generally be referred to as Bulleted List.

It's also consistent with MS Word's behavior.
