### ISSUE TITLE
Subscript

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/editor-recommendations#6]
Honestly I can't think of any use cases for subscript, except mathematical equations, so it's even less useful than "Superscript" feature

There are mainly two options for "Subscript" to be considered:
- [`sub` element](http://www.w3.org/TR/html5/text-level-semantics.html#the-sub-element) - note that spec generally **discourage** to use that element if there are other options
- [subscript Unicode characters](http://www.w3.org/TR/unicode-xml/#Superscripts) - I think that option has limited use cases and support

**Comment by fredck** [comment]
[My comment on Superscript](https://github.com/ckeditor/editor-recommendations/issues/5#issuecomment-161705704) should apply here as well.

**Comment by Comandeer** [comment]
On the second thought, it would be quite useless to have two nearly identical discusses, as my reply to @fredck also apply here as well, so I'm joining "Superscript" and "Subscript" issues.
