### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by jodator** [ckeditor/editor-recommendations#60]
As a foreword: I know that setting font-family is not a best feature to add as it should be preferably set by webpage CSS. But such feature might be required for other use-cases.

I'd like to propose a new feature to be defined: Font that will control font-family of a text.

This feature might not go as part of any of existing use-cases.

**Comment by Comandeer** [comment]
Such presentational-only features goes against [ER's general polices](http://ckeditor.github.io/editor-recommendations/general-policies/) as they don't have any semantic value. Therefore I don't think that they should be included into ER.
