### ISSUE TITLE
Font / Font background color

### ISSUE THREAD

**Issue by jodator** [ckeditor/editor-recommendations#62]
Another set of non-semantic features that might not be in recommended use-cases but are so popular that we could define them.

Also I'm not sure if this this issue is worth to be split to two separate as commonly those are seen in pair.

This features allows to control color of either text or selected text background.

**Comment by Comandeer** [comment]
Such presentational-only features goes against [ER's general polices](http://ckeditor.github.io/editor-recommendations/general-policies/) as they don't have any semantic value. Therefore I don't think that they should be included into ER.
