### ISSUE TITLE
Alignment feature

### ISSUE THREAD

**Issue by jodator** [ckeditor/editor-recommendations#64]
Alignment feature is used to modify alignment of text.

This feature is rather a case for inline-styles rather then defining set of CSS classes to modify alignment. Also for `ltr` and `rtl` scripts the `left` and `right` meaning is the same. Also it might not be a good candidate for recommended features but it would be nice to have this defined.

Implementation

The feature will apply `text-align` CSS property to block elements (`p`, `div`, `h`s).

Default value

If not specified in markup the default value will be `text-align: left` and this will result in removed CSS property.

This might be tricky for RTL text since if I get this correctly the default alignment for `<p dir="rtl">` will be right.

UI/UX - probably a split button would be the best fit.

Also I'd love to see @comandeer input on this.

**Comment by Comandeer** [comment]
Such presentational-only features goes against [ER's general polices](http://ckeditor.github.io/editor-recommendations/general-policies/) as they don't have any semantic value. Therefore I don't think that they should be included into ER.

**Comment by jodator** [comment]
@Comandeer - Yep, you're right. And as such I'm closing it.
