### ISSUE TITLE
Add [rel="noreferrer noopener"] to link feature

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/editor-recommendations#68]
There are two link types – [noopener](http://w3c.github.io/html/links.html#element-statedef-link-noopener) and [noreferrer](http://w3c.github.io/html/links.html#element-statedef-link-noreferrer) – that are created to increase the security of webpages and it's advised to [use them for every external link](https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c). Maybe we could add note to the Link feature:

> The resulting markup SHOULD include `rel` attribute with value set to `"noreferrer noopener"` to prevent vulnerabilities connected with passing referrer to external sites.

I wonder if ER could (should?) include also security recommendations for creating safe HTML? If yes, then addition of such recommendation to the Link feature would be a good start.

**Comment by Reinmar** [comment]
I think it's a very good idea to consider such things in ER.

One question though – what about "safe links" – links within a domain? An editor does not have to add `rel` to all links – in fact, that wouldn't be useful if it did.

**Comment by Comandeer** [comment]
> what about "safe links" – links within a domain?

The super naive approach would be to add `[rel]` attribute only to links with absolute URLs and skip relative ones. Of course editors could also use some heuristic (like `link.hostname === location.hostname`). I think however that it's a technical detail and note that such attribute should be added only to external links will be enough.

**Comment by Reinmar** [comment]
> I think however that it's a technical detail and note that such attribute should be added only to external links will be enough.

Totally agree.

**Comment by fredck** [comment]
Hum... at first I found this a very nice idea. But then, rethinking, it sounded to me that this doesn't seem to be a problem to be solved by the text editor but instead by the application when publishing the content and, when "sanitizing" it, making it also contextual to the publishing website.

In a semantical point of view, when looking at the standalone content one doesn't know where it is supposed to be published, so such attributes will have a misleading semantic value. They are actually a frontend HTML decoration with semantic **contextual** value, so they are pointless without context.

**Comment by Reinmar** [comment]
Oopsie... You're right. I completely forgot about that.

**Comment by Comandeer** [comment]
After rethinking, I must admit that @fredck is right. Closing.
