### ISSUE TITLE
Support native frameworks like Bootstrap

### ISSUE THREAD

**Issue by duracell80** [ckeditor/editor-recommendations#69]
Via configuration changes, have the ability to insert native and compatible elements of frameworks like Bootstrap. Users could then easily style their "links as buttons" with a simple class="btn btn-default". This would stop users from creating buttons in Photoshop because that's their only option if they don't know how to add class="btn btn-default" to the link.

Creating columns is ridiculously complex for users and tables are NOT a good solution. Frameworks like Bootstrap already have columns built in. Why not have a table creator interface but for a 12 column Bootstrap grid?

Users also want to style headings. It's not good enough to add a H1, the H1 or 2 must be able to be changed in style class (from a pre-defined list added by the designer). This would also stop users from making customized headers with "pretty fonts and pretty background images" in Photoshop > inserting image etc.

**Comment by Comandeer** [comment]
Please refer to [Editor's Recommendations General Policies](http://ckeditor.github.io/editor-recommendations/general-policies/).

Such features, not connected with adding semantics to the text (I'm not even sure if they are connected with editing text at all), are out of scope of this project. You're issue looks more like a feature request to Rich Text Editor like [CKEditor 5](https://github.com/ckeditor/ckeditor5).
