### ISSUE TITLE
Ability to add transcript to video audio embed

### ISSUE THREAD

**Issue by duracell80** [ckeditor/editor-recommendations#70]
Beyond helping with accessibility having a text version of the audio content of a video/audio file can help with SEO.

http://www.522productions.com/why-its-important-to-have-a-transcript-of-your-video

**Comment by Comandeer** [comment]
There is no draft or recommendation for multimedia embed, therefore there is no need for adding ability to add transcripts. If there would be proposal for multimedia embed in the future, then transcripts would be also considered.
