### ISSUE TITLE
List Styles > Cycle Through Them on Click

### ISSUE THREAD

**Issue by duracell80** [ckeditor/editor-recommendations#71]
Rather than supporting "ordered" list" and "ordered" lists alone, the styles of those should be supported. Particularity for ordered lists the browser default might be numbers but the user may want roman numerals or an alphabetical order.

To facilitate this without a drop down and because there are a small number of options the user could cycle through these styles on click of the icon with "none" either being the last or first on the cycle, currently the only option is "do you want an un/ordered list or not?".

https://www.w3schools.com/cssref/pr_list-style-type.asp
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol

User expectation on ordered lists is different from ours as developers, sometimes a user may expect that if a list is not ordered that when they click the ordered list icon it will auto-magically reorder. There is also in HTML the missing semantic of order direction (asc/desc) this can be inferred with a class or data attribute.

There is the "start" attribute to consider ... as a user I may not want my list to start at "1" there's a bias in code for all lists to start at 1 but what if I want to split my list and have a paragraph of text between step 6 and 7? I can't my second list would start at 1. This isn't good.

**Comment by Comandeer** [comment]
Please refer to [Editor's Recommendations General Policies](http://ckeditor.github.io/editor-recommendations/general-policies/).

Defining concrete UI implementations and styling considerations are out of scope of this project. You're issue looks more like a feature request to Rich Text Editor like [CKEditor 5](https://github.com/ckeditor/ckeditor5).

This project aims to define basic features in terms of semantics. In that case I propose adding note to lists features about using `[type]` attribute to change list's type.

**Comment by duracell80** [comment]
Moved
