### ISSUE TITLE
Blog/Article

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/editor-recommendations#9]
I've created [first draft for Blog/Article use case](http://ckeditor.github.io/editor-recommendations/use-cases/blog-article.html). Feel free to comment on it!

**Comment by Comandeer** [comment]
I've updated [draft](http://ckeditor.github.io/editor-recommendations/use-cases/blog-article.html) – now it's simpler and more user-friendly.

**Comment by Comandeer** [comment]
Use cases seems to be stable, without any changes. Let's just drop "draft" label from them!

**Comment by OctaneInteractive** [comment]
Hi!

In the first graphic you have what appears to be a block of code (which is what I need to add as a feature in CKEditor), but then under "Features" there's no option for code, which — to me — is confusing.

**Comment by Comandeer** [comment]
I didn't think about it, but actually it is quite confusing. Thanks for noticing it, I'll think about finding better examples for articles.
